version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: scriptdone_soft
    volumes:
      - ./:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: scriptdone_soft_nginx
    ports:
      - "8082:80"

    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
   