version: '3.8'

services:
  php:
   image: php:8.1-fpm
  container_name: scriptdone_php
  volumes:
      - ./public:/var/www/html
  expose:
      - 9001

  nginx:
    image: nginx:latest
    container_name: scriptdone_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php