server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }


#      location ~ \.php$ {
#                 #include snippets/fastcgi-php.conf;
#                 fastcgi_split_path_info ^(.+\.php)(/.+)$;
#                 # With php7.0-cgi alone:
#                 #fastcgi_pass 127.0.0.1:9000;
#                 # With php7.0-fpm:
#                 fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
#                 fastcgi_index index.php;
#                         include fastcgi_params;
#                         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#                         fastcgi_read_timeout 999;
# }
    location ~ /\.ht {
        deny all;
    }
}
